pipeline {

    agent any

    environment {
        VM_IP = "104.215.149.151"
        SSH_CREDENTIALS = "azure-vm-key"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('Amazon') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Amazon') {
                    sh 'mvn test'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'Amazon/Amazon-Web/target/*.war'
            }
        }

        stage('Deploy') {
            steps {
                sshagent(credentials: ['azure-vm-key']) {

                    sh '''
                    scp -o StrictHostKeyChecking=no \
                    Amazon/Amazon-Web/target/*.war \
                    azureuser@$VM_IP:/tmp/
                    '''

                    sh '''
                    ssh -o StrictHostKeyChecking=no \
                    azureuser@$VM_IP \
                    "sudo mv /tmp/*.war /var/lib/tomcat10/webapps/Amazon.war"
                    '''
                }
            }
        }

        stage('Health Check') {
            steps {

                sh "./scripts/health_check.sh $VM_IP"

            }
        }

    }

}
