- hosts: web
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Tomcat
      apt:
        name: tomcat9
        state: present

    - name: Start Tomcat
      service:
        name: tomcat9
        state: started
        enabled: yes

    - name: Copy WAR file
      copy:
        src: ../target/Amazon.war
        dest: /var/lib/tomcat9/webapps/Amazon.war

